### ISSUE TITLE
Segmentation fault (core dumped) - OF7

### ISSUE THREAD

**Issue by Rohit8427** [Franjcf/hybridPorousInterFoam#1]
Problem Description: Error in `hybridPorousInterFoam `solver itself.

To reproduce issue: Enter the command `hybridPorousInterFoam ` in any of the tutorial case or anywhere. 

Build: 7-1ff648926f77
OS: WSL2-Ubuntu 18.04

**Comment by Franjcf** [comment]
Hi! Thanks for the feedback. I could not reproduce your problem in my machine. Did you build the solver in OpenFoam 7 or 8? Did you use the automatic compiling code "Allwmake" that I included in the folder to build the solver and all the associated libraries?

**Comment by Rohit8427** [comment]
I build the solver using OpenFoam 7, and  i used automatic compiling Allwmake as available in folder for it in wsl 1,2 Ubuntu 18.04 and also in centos 7 on different machines.

**Comment by Rvadrabade** [comment]
To add to above discussion. We are able to compile solver successfully however not able to run it. We are getting Segmentation fault (core dumped) with latest OF7 Build: 7-1ff648926f77.

**Comment by Franjcf** [comment]
Ok, this is unexpected. Could you post the following things so I can get a better idea of your problem? 

1) The complete error prompt that the terminal gives you once you run hybridPorousInterFoam
2) The list of solvers under $FOAM_USER_APPBIN
3) The list of libraries under $FOAM_USER_LIBBIN

Can you run standard solvers such as interFoam in the standard tutorials included in OF7?

**Comment by Rohit8427** [comment]
1. The complete error prompt that the terminal gives is: Segmentation fault (core dumped)
2. List of solvers: `hybridPorousInterFoam `and `hybridPorousPimpleFoam`
3. List of libraries: `porousImmiscibleIncompressibleTwoPhaseMixture`, `porousInterfaceProperties`,  `porousModels  `and `porousTwoPhaseProperties`

Yes, I am able to  run standard solver interFoam in the standard tutorials included in OF7.

Please also share your email id with me if you can, so that I can share terminal's screenshot with you.

**Comment by Franjcf** [comment]
Hi, Sorry for the long delay. I have been pretty busy these last couple of months. You can email me at franjcf "at" princeton.edu, but I'm fairly sure you can include files through this chat as well. Before you do that though I would ask you to make sure your simulation is set up as a laminar flow. The solver currently does not support turbulence models. I have seen other people run into this same problem.

**Comment by ZZZYunpeng** [comment]
Hi, Dr. Franjcf. I am using this solver, too. I met the same problem. When I run hybridPorousInterFoam, the error will show "Segmentation fault (core dumped)". Then I run the command "ulimit -c unlimited". But it still is not solved. Do you know what is the reason and how to solve it, please?
