### ISSUE TITLE
EXE = $(FOAM_APPBIN)/SRFPimpleFoam OF8

### ISSUE THREAD

**Issue by Rohit8427** [Franjcf/hybridPorousInterFoam#2]
Problem Solution: Error resolved by correcting title command to  EXE = `$(FOAM_USER_APPBIN)/SRFPimpleFoam` in OpenFoamV8/HybridPorousPimpleFoam/SRFPimpleFoam/Make/files

To reproduce issue: Enter the command `hybridPorousInterFoam ` in any of the tutorial case or anywhere. 

Build: 8-9b73cf21a682
OS: WSL1-Ubuntu 18.04

**Comment by Rvadrabade** [comment]
Specifically, unable to build [SRFPimpleFoam](https://github.com/Franjcf/hybridPorousInterFoam/commits/master/OpenFoamV8/solvers/hybridPorousPimpleFoam/SRFPimpleFoam/Make/files)

**Comment by Franjcf** [comment]
Hi! Thank you for the feedback. This was my mistake. SRFPimpleFoam is actually a left-over solver that should not have been included in this toolbox. I updated the toolbox so that the newest version does not include it.
